apiVersion: remote-build.pongle-hub.co.uk/v1alpha1
kind: BuildInstance
metadata:
  name: example-buildinstance
  namespace: user-1
  labels:
    app.kubernetes.io/managed-by: remote-build
spec:
  cpu: "500m"
  memory: "128Mi"
  disk: "1Gi"
  image: "moby/buildkit:master-rootless"