apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: buildinstances.remote-build.pongle-hub.co.uk
spec:
  group: remote-build.pongle-hub.co.uk
  scope: Namespaced
  names:
    plural: buildinstances
    singular: buildinstance
    kind: BuildInstance
    shortNames:
    - bi
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cpu:
                type: string
                description: "Number of CPU cores to allocate (e.g., '2', '500m')"
              memory:
                type: string
                description: "Amount of memory to allocate (e.g., '512Mi', '2Gi')"
              disk:
                type: string
                description: "Amount of disk space to allocate (e.g., '1Gi', '10Gi')"
              image:
                type: string
                description: "Container image to use for the build instance (e.g., 'moby/buildkit:master-rootless')"
            required: []
          status:
            type: object
            properties:
              state:
                type: string
                description: "Current state of the build instance (e.g., 'Pending', 'Running', 'Failed')"
              active:
                type: boolean
                description: "Indicates if the build instance is active"
    additionalPrinterColumns:
    - name: State
      type: string
      description: Current state of the build instance
      jsonPath: .status.state
    - name: Active
      type: boolean
      description: Indicates if the build instance is active
      jsonPath: .status.active
# ---
# Example:
# apiVersion: remote-build.pongle-hub.co.uk/v1alpha1
# kind: BuildInstance
# metadata:
#   name: example-buildinstance
# spec:
#   cpu: "3"
#   memory: "512Mi"
#   disk: "1Gi"
#   image: "moby/buildkit:master-rootless"
